---
all:
  children:
    master:
      hosts:
        kubemaster-ansible:
          ansible_host: 192.168.64.67
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_multipass
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    workers:
      hosts:
        kubeworker1-ansible:
          ansible_host: 192.168.64.68
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_multipass
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        kubeworker2-ansible:
          ansible_host: 192.168.64.69
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_multipass
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
