---
- name: Configure Kubernetes prerequisites on all nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure required kernel modules are loaded at boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules now
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set sysctl params for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl params
      command: sysctl --system

    - name: Print module check output
      debug:
        var: module_check.results

    - name: Verify sysctl values
      command: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
      register: sysctl_output

    - name: Print sysctl values
      debug:
        var: sysctl_output.stdout_lines
